language: python
python:
- '3.6'
install:
- pip install -r twote_requirements.txt
- echo "import nltk; nltk.download('punkt')" | python manage.py shell
script:
- python manage.py test openspaces/bot_utils/
- python manage.py test openspaces/tests/
- python tests_streambot.py
before_install:
- openssl aes-256-cbc -K $encrypted_9a2b31df230e_key -iv $encrypted_9a2b31df230e_iv
  -in local_settings.py.enc -out openchat/local_settings.py -d
- openssl aes-256-cbc -K $encrypted_9a2b31df230e_key -iv $encrypted_9a2b31df230e_iv
  -in secrets.py.enc -out openspaces/secrets.py -d
