version: '2'

services:
  db:
    image: postgres

  web:
    build:
      context: ./
      dockerfile: ./deploy/openchat/Dockerfile
    image: openchat_web
    command: gunicorn openchat.wsgi -b 0.0.0.0:8000 --log-level=debug -k 'eventlet'
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    links:
      - rabbit
    depends_on:
      - db
      - migration
    environment:
      - DOCKER_DEV=true

  migration:
    image: openchat_web
    command: python manage.py migrate --no-input
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - DOCKER_DEV=true

  rabbit:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"
      - "15672:15672"  # here, we can access rabbitmq management plugin

  nginx:
    build:
      context: ./
      dockerfile: ./deploy/nginx/Dockerfile
    volumes:
      - .:/code
    links:
      - web
    ports:
      - "80:80"
      - "443:443"
