version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    image: openchat_web
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - migration
  migration:
    image: openchat_web
    command: python manage.py migrate --no-input
    volumes:
      - .:/code
    depends_on:
      - db